[general]
import = [
    "~/.local/share/alacritty/active-theme.toml",
]

[font]
size = 13.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.offset]
x = 0
y = 1

[window]
decorations = "Buttonless"
dynamic_title = true
opacity = 0.95

[env]
TERM = "xterm-256color"

[cursor.style]
shape = "Block"
blinking = "On"

[cursor.vi_mode_style]
shape = "Block"

[scrolling]
history = 10000

[mouse]
hide_when_typing = true
