{ lib }:
let
  renderColors =
    theme:
    let
      f = theme.format;
      p = theme.palette;
      t = theme.roles.ui;
      s = theme.roles.status;
      lines = [
        [
          "BLACK"
          (f.sketchybar t.backgroundStrong "ff")
        ]
        [
          "WHITE"
          (f.sketchybar t.foreground "ff")
        ]
        [
          "RED"
          (f.sketchybar s.danger "ff")
        ]
        [
          "GREEN"
          (f.sketchybar s.success "ff")
        ]
        [
          "BLUE"
          (f.sketchybar s.info "ff")
        ]
        [
          "YELLOW"
          (f.sketchybar s.warning "ff")
        ]
        [
          "ORANGE"
          (f.sketchybar p.peach "ff")
        ]
        [
          "MAGENTA"
          (f.sketchybar t.accent "ff")
        ]
        [
          "GREY"
          (f.sketchybar p.overlay2 "ff")
        ]
        [
          "TRANSPARENT"
          "0x00000000"
        ]
        [
          "BAR_BG"
          (f.sketchybar t.background "15")
        ]
        [
          "STATUS_BG"
          (f.sketchybar t.background "22")
        ]
        [
          "STATUS_GRAPH_BG"
          (f.sketchybar t.background "16")
        ]
        [
          "POPUP_BG"
          (f.sketchybar t.background "70")
        ]
        [
          "SPACE_INITIAL_BG"
          (f.sketchybar t.foreground "44")
        ]
        [
          "SPACE_FOCUSED_BG"
          (f.sketchybar t.foreground "55")
        ]
        [
          "SPACE_VISIBLE_BG"
          (f.sketchybar t.foreground "22")
        ]
        [
          "MODE_BG"
          (f.sketchybar t.accent "24")
        ]
        [
          "CPU_SYSTEM_FILL"
          (f.sketchybar s.danger "20")
        ]
        [
          "CPU_USER_FILL"
          (f.sketchybar s.info "20")
        ]
        [
          "NET_DOWNLOAD_FILL"
          (f.sketchybar s.info "20")
        ]
        [
          "NET_UPLOAD_FILL"
          (f.sketchybar s.success "20")
        ]
        [
          "DEFAULT_ICON_COLOR"
          (f.sketchybar t.foreground "ff")
        ]
        [
          "DEFAULT_LABEL_COLOR"
          (f.sketchybar t.foreground "ff")
        ]
      ];
    in
    lib.concatStringsSep "\n" (
      [ "# Generated by Home Manager; source config/sketchybar/colors.sh instead." ]
      ++ map (line: "${builtins.elemAt line 0}=${builtins.elemAt line 1}") lines
    );
in
{
  colors = theme: renderColors theme + "\n";
}
