# Generated by Home Manager from the romaingrx theme contract.
# Sourced by the 70-borders reload hook through the runtime `current`
# symlink to drive jankyborders colors for the active appearance.
BORDER_ACTIVE_COLOR=0xff8839ef
BORDER_INACTIVE_COLOR=0xff9ca0b0
