repos:
  - repo: local
    hooks:
      - id: nix-fmt
        name: nix fmt
        entry: nix fmt --
        language: system
        files: \.nix$
        exclude: ^third-party/
      - id: deadnix
        name: deadnix
        entry: deadnix --fail
        language: system
        files: \.nix$
        exclude: ^third-party/
      - id: statix
        name: statix check
        entry: statix check .
        language: system
        files: \.nix$
        exclude: ^third-party/
        pass_filenames: false
