{ lib }:
let
  renderColors =
    theme:
    let
      f = theme.format;
      t = theme.roles.ui;
    in
    ''
      # Generated by Home Manager from the romaingrx theme contract.
      # Sourced by the 70-borders reload hook through the runtime `current`
      # symlink to drive jankyborders colors for the active appearance.
      BORDER_ACTIVE_COLOR=${f.argb t.border "ff"}
      BORDER_INACTIVE_COLOR=${f.argb t.borderInactive "ff"}
    '';
in
{
  colors = theme: lib.trim (renderColors theme) + "\n";
}
