# Generated by Home Manager; source config/sketchybar/colors.sh instead.
BLACK=0xff181825
WHITE=0xffcdd6f4
RED=0xfff38ba8
GREEN=0xffa6e3a1
BLUE=0xff89b4fa
YELLOW=0xfff9e2af
ORANGE=0xfffab387
MAGENTA=0xffcba6f7
GREY=0xff9399b2
TRANSPARENT=0x00000000
BAR_BG=0x151e1e2e
STATUS_BG=0x221e1e2e
STATUS_GRAPH_BG=0x161e1e2e
POPUP_BG=0x701e1e2e
SPACE_INITIAL_BG=0x44cdd6f4
SPACE_FOCUSED_BG=0x55cdd6f4
SPACE_VISIBLE_BG=0x22cdd6f4
MODE_BG=0x24cba6f7
CPU_SYSTEM_FILL=0x20f38ba8
CPU_USER_FILL=0x2089b4fa
NET_DOWNLOAD_FILL=0x2089b4fa
NET_UPLOAD_FILL=0x20a6e3a1
DEFAULT_ICON_COLOR=0xffcdd6f4
DEFAULT_LABEL_COLOR=0xffcdd6f4

# Font family from the central theme contract (lib/theme/fonts.nix).
FONT="FiraCode Nerd Font"
NERD_FONT="FiraCode Nerd Font"
