{ lib }:
let
  renderFlavor = theme: ''
    # vim:set ft=tmux:
    # Generated by Home Manager from the romaingrx theme contract.
    # Sourced by tmux through the runtime `current` symlink; selects the
    # Catppuccin flavor that matches the active appearance.
    set -g @catppuccin_flavor '${theme.tmuxFlavor}'
  '';

  # The contract integration drop-in. tmux.conf sources this through
  # $ROMAINGRX_THEME_TMUX_CONF, so the committed config stays free of any
  # runtime paths or theme-CLI names and works standalone on a vanilla checkout.
  # All concrete paths are injected here by Home Manager (absolute, so the
  # global prefix+T toggle does not depend on PATH).
  renderIntegration =
    {
      flavorConf,
      themeGet,
      themeSet,
    }:
    ''
      # vim:set ft=tmux:
      # Generated by Home Manager - romaingrx theme contract integration for tmux.

      # Drive the Catppuccin flavor from the active runtime appearance.
      source-file -q '${flavorConf}'

      # prefix + T flips the *global* appearance so every consumer re-themes
      # together.
      bind T run-shell 'if [ "$(${themeGet})" = dark ]; then ${themeSet} light; else ${themeSet} dark; fi'
    '';
in
{
  flavor = theme: lib.trim (renderFlavor theme) + "\n";
  integration = args: lib.trim (renderIntegration args) + "\n";
}
