# Generated by Home Manager from the romaingrx theme contract.
# Sourced by the 70-borders reload hook through the runtime `current`
# symlink to drive jankyborders colors for the active appearance.
BORDER_ACTIVE_COLOR=0xffcba6f7
BORDER_INACTIVE_COLOR=0xff6c7086
