{
  config,
  dotfilesPath,
  lib,
  ...
}:
let
  cfg = config.romaingrx.theme;
  theme = import ../../../lib/theme { };
  homeRelativePath = lib.types.strMatching "[^/].*";
  homePath = path: "${config.home.homeDirectory}/${path}";
  absoluteGeneratedRoot = homePath cfg.generatedRoot;
  absoluteReloadHookLog = homePath cfg.reloadHookLog;
  absoluteReloadHooksRoot = homePath cfg.reloadHooksRoot;
  absoluteRuntimeRoot = homePath cfg.runtimeRoot;
  themeLib = "${dotfilesPath}/config/bin/romaingrx-theme-lib";
  toShellEnv = lib.generators.toKeyValue {
    mkKeyValue = name: value: "${name}=${lib.escapeShellArg value}";
  };
in
{
  options.romaingrx.theme = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Whether to enable the centralized romaingrx theme contract.";
    };

    defaultAppearance = lib.mkOption {
      type = lib.types.enum theme.appearanceNames;
      default = "dark";
      description = "The appearance used for first-run theme bootstrap.";
    };

    generatedRoot = lib.mkOption {
      type = homeRelativePath;
      default = ".config/romaingrx/theme/generated";
      description = "Home-relative directory for generated theme artifacts.";
    };

    runtimeRoot = lib.mkOption {
      type = homeRelativePath;
      default = ".local/state/theme";
      description = "Home-relative directory for runtime theme state and active symlinks.";
    };

    reloadHooksRoot = lib.mkOption {
      type = homeRelativePath;
      default = ".config/romaingrx/theme/reload-hooks";
      description = "Home-relative directory containing executable hooks run after a theme apply.";
    };

    reloadHookLog = lib.mkOption {
      type = homeRelativePath;
      default = ".local/state/theme/reload-hooks.log";
      description = "Home-relative file where theme reload hook failures are logged.";
    };

    runtimeEnv = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = { };
      description = "Shell variables written to the runtime theme contract.";
    };
  };

  config = lib.mkIf cfg.enable {
    romaingrx.theme.runtimeEnv = {
      ROMAINGRX_THEME_DEFAULT_APPEARANCE = cfg.defaultAppearance;
      ROMAINGRX_THEME_GENERATED_ROOT = absoluteGeneratedRoot;
      ROMAINGRX_THEME_RELOAD_HOOK_LOG = absoluteReloadHookLog;
      ROMAINGRX_THEME_RELOAD_HOOKS_DIR = absoluteReloadHooksRoot;
      ROMAINGRX_THEME_RUNTIME_ROOT = absoluteRuntimeRoot;
    };

    home = {
      file.".config/romaingrx/theme/paths.env".text = ''
        # Generated by Home Manager; sourced by romaingrx-theme-lib.
        ${toShellEnv cfg.runtimeEnv}
      '';

      activation = {
        romaingrxThemeBootstrap = lib.hm.dag.entryAfter [ "linkGeneration" ] ''
          # shellcheck source=/dev/null
          source "${themeLib}"
          theme_bootstrap_state
        '';

        romaingrxThemeReloadHooks =
          lib.hm.dag.entryAfter
            [
              "linkGeneration"
              "romaingrxThemeBootstrap"
            ]
            ''
              # shellcheck source=/dev/null
              source "${themeLib}"
              theme_reload_consumers "$(theme_read_state)"
            '';
      };
    };
  };
}
