name: check
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
        with:
          name: romaingrx-dotfiles
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Pre-commit hooks
        run: nix flake check --print-build-logs --option abort-on-warn true

      - name: Evaluate host configurations
        run: |
          set -e
          for host in $(nix eval --json .#nixosConfigurations --apply builtins.attrNames | nix run nixpkgs#jq -- -r '.[]'); do
            echo "::group::nixosConfigurations.$host"
            nix eval --raw ".#nixosConfigurations.$host.config.system.build.toplevel.drvPath" --option abort-on-warn true
            echo
            echo "::endgroup::"
          done
          for host in $(nix eval --json .#darwinConfigurations --apply builtins.attrNames | nix run nixpkgs#jq -- -r '.[]'); do
            echo "::group::darwinConfigurations.$host"
            nix eval --raw ".#darwinConfigurations.$host.system.drvPath" --option abort-on-warn true
            echo
            echo "::endgroup::"
          done
