name: nixfmt
on:
  push:

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30

      - run: "nix run nixpkgs#nixfmt-rfc-style -- --check **/*.nix"
        id: check
