name: nixfmt
on:
  push:

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30

      - run: "find . -name '*.nix' -not -path './third-party/*' -print0 | xargs -0 nix fmt -- --check"
        id: check
