test: ENC[AES256_GCM,data:I3nLkJ0NWQ==,iv:Kf9yKAQUv3uuP7XFrqUdG7IzwlxYB+f1DR6k6TuV51s=,tag:nyJJPmR29Nh1pv4IMfVmXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18r9akfvujxryr4kpc4a34agsvkqczkl6gf8aaq98jmaqyl4tt42snpac6f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUFN0L2tTaStuWEtNRGI5
            K3BYL1JrNlE1amRjWUlMMjQxblozYS9JUUhNClptZktoeUFFcFYydUlOZ0FuaU5r
            aGovOGRFRmxhUUdrWFZBSmdpOXR6Q2MKLS0tIDU0MlVGRVZ1b0pVUDBacDRXbU1R
            em9ncWRweTNKZXhMVHJRVklPdnBnbm8KC++Q4h4S4bgKOn9O2gKPaBKl9wmSaNYx
            RKlUFhAe5KhkD/y6QJIIo4rUzjt63pvDsurc26KpkJIZ4j/Trd54nA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1md2t0hzlag085jflzvk2unss9v2gqpe8qscxzzeues2nzpfgt3nqeu2h9h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZE5va0prK2ZaZGkxVXkz
            OFFxWUpPUDV2UVhQaGRtcFNwKzlrREp2RkNZCkppdEo2b05uc0p2TXhSMEVDNS8z
            a3JmOVVkS2t0QlViaHpIK240NXdUWTgKLS0tIGplcFIveEVsNzBUZEhDWHIvTDNS
            b0oybEFEamxFQk1sRWNCS2lVZSttTUkK0sha71FBGpyWRddMrR0nJ6DhI9G7xaS6
            hWEIhqwKoKrXiO+AQNDwaMJHHpERc9HCMXh1m+LG6R+B6g7D7Qqybw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-18T09:38:27Z"
    mac: ENC[AES256_GCM,data:LcI9U6kwzCVVedPKgZmSi/2HGeG6yX1H3YeBRqyjg7po3aMrWAoRAvXiD2/ke7swrlUBA3ooNhKTBCV+o8VtN6hfrMfHxpnr7uc2v7Pyhn8O9JIKrYltZhUEfxcRrhYceDH0CgfavFjcs7BCJfuEFp4W9SwjHVauI2WdfFxknaY=,iv:ZFXa/tx565c2vMzyS/mon8/3a4D7L/Oo3+/gneU8xYo=,tag:GIjZM+7qIn76YUWVHGkzfg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
