test: ENC[AES256_GCM,data:guWNfjTkmg==,iv:cJfa4d+ArAnKxl3MSmZF2mHmM0Ul4/KpBNwt4lawhnk=,tag:xLxePYBWTXdZrSV7o4ROXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18r9akfvujxryr4kpc4a34agsvkqczkl6gf8aaq98jmaqyl4tt42snpac6f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUFN0L2tTaStuWEtNRGI5
            K3BYL1JrNlE1amRjWUlMMjQxblozYS9JUUhNClptZktoeUFFcFYydUlOZ0FuaU5r
            aGovOGRFRmxhUUdrWFZBSmdpOXR6Q2MKLS0tIDU0MlVGRVZ1b0pVUDBacDRXbU1R
            em9ncWRweTNKZXhMVHJRVklPdnBnbm8KC++Q4h4S4bgKOn9O2gKPaBKl9wmSaNYx
            RKlUFhAe5KhkD/y6QJIIo4rUzjt63pvDsurc26KpkJIZ4j/Trd54nA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1md2t0hzlag085jflzvk2unss9v2gqpe8qscxzzeues2nzpfgt3nqeu2h9h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZE5va0prK2ZaZGkxVXkz
            OFFxWUpPUDV2UVhQaGRtcFNwKzlrREp2RkNZCkppdEo2b05uc0p2TXhSMEVDNS8z
            a3JmOVVkS2t0QlViaHpIK240NXdUWTgKLS0tIGplcFIveEVsNzBUZEhDWHIvTDNS
            b0oybEFEamxFQk1sRWNCS2lVZSttTUkK0sha71FBGpyWRddMrR0nJ6DhI9G7xaS6
            hWEIhqwKoKrXiO+AQNDwaMJHHpERc9HCMXh1m+LG6R+B6g7D7Qqybw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-15T17:00:20Z"
    mac: ENC[AES256_GCM,data:+rtsFLhMh+SM9FyAXSe3sqnBENWPJQcm9X4oJhPw3wBxfZITYfHMyVCZTyfqZLPCWXTbtKqOG6oaJwrRJ6PyT1z2OfJgTS15XIjbseh5CJNqemNYGH4rtbE5sD7AqvuI2iTBupDlD+aGnBudslPbJmOb+VNSo+LPiIOCdvPlGZo=,iv:WCGrL5BYGPhi0HpN4qnDfgcw0KY+DyOdSeyUr9TvRLw=,tag:mWsXF7LU5gM9LbzNCWAI4Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
